
version: '3.8'
services:
  bd:
    build:
      context: ../Banco-IT_Talent/
      # image: desafio_it_talent_junho_01

    container_name: bd
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  backend:
    build:
      context: .
      # image: backend_desafio_it_talent_junho_01

    container_name: backend
    depends_on: 
      - bd
    ports:
      - "8080:8080"
    environment:
      APP_PORT: ${APP_PORT}